spring:
  profiles:
    active: common, secret

---
spring.config.activate.on-profile: common

spring:
  application.name: igjampel
  security:
    oauth2:
      client:
        registration:
          google:
            scope: openid, profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

server.port: 8094
